// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lahntbtkexelailmzrew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhaG50YnRrZXhlbGFpbG16cmV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4MzY3NTksImV4cCI6MjA3NTQxMjc1OX0.R26nB5jmJbrZS-C-EbLZQ67rcuWn8C-iRJ-hLuBXWlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});